apply plugin: 'com.android.application'

android {
    namespace 'com.pocket.launcher'
    compileSdk 34
    defaultConfig {
        applicationId "com.pocket.launcher"
        minSdk 26 // Android 8.0
        targetSdk 34
        versionCode 1
        versionName "1.0"
        
        // ESSENCIAL PARA O SAMSUNG A13
        ndk {
            abiFilters "armeabi-v7a"
        }
        
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
            }
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
}
